controller_manager:
  ros__parameters:
    update_rate: 100

    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gantry_controller:  
      type: joint_trajectory_controller/JointTrajectoryController


gantry_controller:
  ros__parameters:
    joints:
      - x_joint
      - y_joint
      - z_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity